### ISSUE TITLE
Made a simple animated mp4/gif to demonstrate wiki-hub

### ISSUE THREAD

**Issue by erlend-sh** [mushishi78/wikihub#4]
GIF:
![wikihub-piclite-gif-crop](https://cloud.githubusercontent.com/assets/583842/9761287/1bf37096-56fc-11e5-9081-93268ec386c6.gif)

MP4:
https://github.com/erlend-sh/erlend-sh.github.io/blob/master/images/wikihub-presentation.mp4

**Comment by mushishi78** [comment]
Cool, but it made my browser tab crash eating memory, could you compress it or something?

I'll give you push access to wiki-hub so you put this in the readme and make any documentation or presentation changes you see fit.

**Comment by erlend-sh** [comment]
> it made my browser tab crash eating memory

Really? That's odd. Well the mp4 is quite compressed already, but gifs work in mysterious ways... And yeah, I'm noticing a distinct slowdown as well. It's causing hangups in GitHub's editor.

I tried making one video Imgur's video-to-gif converter instead, but it's super strange. The more I pre-compress the .mp4 file I feed it, the bigger the gif turns out!

http://imgur.com/Of336jY

**Comment by mushishi78** [comment]
My computer can handle the gif in imgur, thanks. It could just be that my
computer's too old, I am running window vista...

**Comment by erlend-sh** [comment]
The one on imgur is 15 mb though ^^ I made yet another gif in the Nth gif creator I tried, and got it down to 1mb with reasonable quality. Will use that one, since I don't wanna impose a 15mb load on unsuspecting GitHub visitors.
