### ISSUE TITLE
Wikihub logo

### ISSUE THREAD

**Issue by erlend-sh** [mushishi78/wikihub#6]
I [linked to wikihub on Reddit](https://www.reddit.com/r/github/comments/3kdzzq/wikihub_enables_inpage_editing_for_any_static/) and noticed that the thumbnail is completely generic, so I made a simple logo for the Wikihub org.

400px:

![wikihub-logo](https://cloud.githubusercontent.com/assets/583842/9788256/a7bdb54c-57c8-11e5-87b2-fe3a7b4d411b.png)

1600px:

![wikihub-logo](https://cloud.githubusercontent.com/assets/583842/9788247/90e1011c-57c8-11e5-8199-71ca95bff805.png)

Based on this:

https://openclipart.org/detail/37105/lettre

**Comment by mushishi78** [comment]
Awesome!

**Comment by mvaneijgen** [comment]
Im going to use wikihub in my next project and needed to give some credit, so I made a `SVG` version because `SVG` for the win! 

![wikihub logo svg](https://dl.dropboxusercontent.com/u/345640/wiki-hub.svg)

Hope it helps,

**Comment by mushishi78** [comment]
Cool thanks :+1:
